services:
  postgres:
    image: 'postgres:17.11-alpine3.23'
    environment:
      - 'POSTGRES_DB=bookdb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=app'
    ports:
      - '15432:5432'
